### ISSUE TITLE
[Bug] tree level of objects in editor

### ISSUE THREAD

**Issue by HPrivakos** [decentraland/feedback#1]
After publishing my "work" I tried to edit it again, but the tree of objects changed, and all is now broken
Parcel: [0,1]
It had this form:
```
|_ sphere
|_ sphere
|_ sphere
```
And now look like:
```
|_ sphere
    |_ sphere
        |_ sphere
```

**Comment by HAZARDU5** [comment]
I've had the same problem. Seemed to be fixed after going back in via edit mode, deleting the objects and re-adding them.

**Comment by eordano** [comment]
Fixed now
