### ISSUE TITLE
[Bug] Some OBJs appear fine in the editor, but have incorrect orientation in the client

### ISSUE THREAD

**Issue by HAZARDU5** [decentraland/feedback#11]
E.g. this snowman OBJ from Poly: https://poly.google.com/view/cGQEmccC8EM

It requires it to be rotated as follows to be right side up: x: -90. y: 180, z: 180

I suspect there is a difference between the client and the editor in terms of the axis order for Euler rotations or alternately the client is messing with the values pulled down from IPFS in certain cases.

This seems to happen regardless of the scale of the OBJ.

**Comment by bnolan** [comment]
Fixed, client wasn't specifying euler order as per aframe.
