### ISSUE TITLE
Client is not working at the moment?

### ISSUE THREAD

**Issue by Alonzo-Coeus** [decentraland/feedback#12]
![image](https://user-images.githubusercontent.com/18367713/33514427-b89a74fe-d74b-11e7-9a28-9af16fd07f67.png)

**Comment by HAZARDU5** [comment]
Seems like it's working for me in Chrome. Can you also try: https://client.decentraland.today/branch/feature/fly/index.html

**Comment by eordano** [comment]
Fixed, yes, it was down on Saturday.
