### ISSUE TITLE
[Bug] When no results are returned for Poly model searches an error occurs

### ISSUE THREAD

**Issue by HAZARDU5** [decentraland/feedback#19]
I receive the following error:

```
Uncaught (in promise) TypeError: Cannot read property 'map' of undefined
    at ModelSidebar.render (aframe-inspector.js:114821)
```
Seems like empty lists returned from the Poly API aren't being handled by the editor.

You can replicate this by searching for a term with no results e.g. `hazardu5`

It's worth noting that recently published models in Blocks don't appear as results on the Poly API for several minutes while their cache refreshes. It could be worth including some messaging in the editor about this.

**Comment by bnolan** [comment]
Thanks @HAZARDU5! Fixed.
