### ISSUE TITLE
[Feature] No error message when uploaded model is too large

### ISSUE THREAD

**Issue by HAZARDU5** [decentraland/feedback#2]
I get the following error in the JS console when uploading large models:

```
Failed to load resource: the server responded with a status of 413 (Request Entity Too Large)
```

It'd be great to show this in the editor.

**Comment by HAZARDU5** [comment]
This is also a problem when importing models via the Poly API search.

**Comment by eordano** [comment]
@HAZARDU5 can you send a sample file with which you're having this issue?

**Comment by HAZARDU5** [comment]
The model from here has the issue: https://poly.google.com/view/2hWxc7Hk9CJ
If you download the OBJ of it you'll see what I mean.

**Comment by bnolan** [comment]
Fixed, thanks!

**Comment by bnolan** [comment]
![screen shot 2017-12-12 at 5 39 40 pm](https://user-images.githubusercontent.com/17499/33867899-7552ec5a-df64-11e7-85dd-73e8f5a02303.png)
