### ISSUE TITLE
[Bug] Cannot save XX objects do not fit inside your parcel boundaries

### ISSUE THREAD

**Issue by HAZARDU5** [decentraland/feedback#20]
For some reason, even after I move all my objects inside the parcel boundaries (marked with the magenta border) I receive this message. Is there some kind of height limit now in place?

**Comment by HAZARDU5** [comment]
I've tested this further and even with removing all objects from a single LAND parcel, then inserting a basic cube, I'm still unable to save and get the following message:

```
Cannot save 1 objects do not fit inside your parcel boundaries
```

This is pretty much blocking me from doing any other testing right now.

**Comment by eordano** [comment]
Confirmed I can't either. Taking a look now

**Comment by bnolan** [comment]
Fixed!
